{
  "backend": {
    "name": "git-gateway",
    "accept_roles": [
      "admin",
      "editor"
    ]
  },
  "media_folder": "static/images/uploads",
  "collections": [
    {
      "name": "pages",
      "label": "Pages",
      "folder": "site/pages",
      "create": false,
      "delete": false,
      "slug": "{{slug}}",
      "editor": {
        "preview": false
      },
      "fields": [
        {
          "label": "Title",
          "name": "title",
          "widget": "string"
        },
        {
          "label": "Publish Date",
          "name": "date",
          "widget": "datetime"
        },
        {
          "label": "Layout",
          "widget": "hidden",
          "name": "layout",
          "default": "{{slug}}.html"
        },
        {
          "label": "Seo",
          "name": "seo",
          "widget": "object",
          "fields": [
            {
              "label": "Title",
              "name": "title",
              "widget": "string",
              "required": false
            },
            {
              "label": "Description",
              "name": "description",
              "widget": "string",
              "required": false
            },
            {
              "label": "Open Graph Image",
              "name": "og:image",
              "widget": "image",
              "required": false,
              "media_library": {
                "config": {
                  "multiple": false
                }
              }
            },
            {
              "label": "Twitter Card",
              "name": "twitter:card",
              "widget": "string",
              "default": "summary",
              "required": false
            },
            {
              "label": "Twitter Site",
              "name": "twitter:site",
              "widget": "string",
              "required": false
            },
            {
              "label": "Twitter Creator",
              "name": "twitter:creator",
              "widget": "string",
              "required": false
            },
            {
              "label": "Additional HTML tags",
              "name": "additional_tags",
              "widget": "text",
              "required": false
            }
          ]
        }
      ]
    },
    {
      "name": "projects",
      "label": "Projects",
      "folder": "site/projects",
      "create": true,
      "slug": "{{slug}}",
      "editor": {
        "preview": false
      },
      "fields": [
        {
          "label": "Title",
          "name": "title",
          "widget": "string"
        },
        {
          "label": "Tags",
          "widget": "hidden",
          "name": "tags",
          "default": "projects"
        },
        {
          "label": "Publish Date",
          "name": "date",
          "widget": "datetime"
        },
        {
          "label": "Layout",
          "widget": "hidden",
          "name": "layout",
          "default": "single-projects.html"
        },
        {
          "label": "Seo",
          "name": "seo",
          "widget": "object",
          "fields": [
            {
              "label": "Title",
              "name": "title",
              "widget": "string",
              "required": false
            },
            {
              "label": "Description",
              "name": "description",
              "widget": "string",
              "required": false
            },
            {
              "label": "Open Graph Image",
              "name": "og:image",
              "widget": "image",
              "required": false,
              "media_library": {
                "config": {
                  "multiple": false
                }
              }
            },
            {
              "label": "Twitter Card",
              "name": "twitter:card",
              "widget": "string",
              "default": "summary",
              "required": false
            },
            {
              "label": "Twitter Site",
              "name": "twitter:site",
              "widget": "string",
              "required": false
            },
            {
              "label": "Twitter Creator",
              "name": "twitter:creator",
              "widget": "string",
              "required": false
            },
            {
              "label": "Additional HTML tags",
              "name": "additional_tags",
              "widget": "text",
              "required": false
            }
          ]
        },
        {
          "name": "project-name",
          "label": "Project name",
          "widget": "text",
          "required": false
        },
        {
          "name": "main-image",
          "label": "Main image",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "property-type",
          "label": "Property type",
          "widget": "text",
          "required": false
        },
        {
          "name": "price-range",
          "label": "Price range",
          "widget": "text",
          "required": false
        },
        {
          "name": "bedroom",
          "label": "Bedroom",
          "widget": "text",
          "required": false
        },
        {
          "name": "area",
          "label": "Area",
          "widget": "text",
          "required": false
        },
        {
          "name": "location",
          "label": "Location",
          "widget": "text",
          "required": false
        },
        {
          "name": "possession",
          "label": "Possession",
          "widget": "text",
          "required": false
        },
        {
          "name": "project-image-1",
          "label": "Project image 1",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-2",
          "label": "Project image 2",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-3",
          "label": "Project image 3",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-4",
          "label": "Project image 4",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-5",
          "label": "Project image 5",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-6",
          "label": "Project image 6",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-7",
          "label": "Project image 7",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-8",
          "label": "Project image 8",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-9",
          "label": "Project image 9",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-10",
          "label": "Project image 10",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-11",
          "label": "Project image 11",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-12",
          "label": "Project image 12",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-13",
          "label": "Project image 13",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-14",
          "label": "Project image 14",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-image-15",
          "label": "Project image 15",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "label": "Body",
          "name": "body",
          "widget": "markdown",
          "required": false
        }
      ]
    }
  ]
}